all:
	gcc ${CFLAGS} -O0 -Wall dpcsync.c -o dpcsync -ggdb3 -I../../driver/
	gcc ${CFLAGS} -O0 -Wall videoout.c -o videoout -ggdb3 -I../../driver/
	gcc ${CFLAGS} -O0 -Wall getconst.c -o getconst -ggdb3 -I../../driver/
	gcc ${CFLAGS} -O0 -Wall setconst.c -o setconst -ggdb3 -I../../driver/

clean:
	rm -f dpcsync videoout getconst setconst

