all:
	gcc -O2 -Wall dpcsync.c -o dpcsync -ggdb3 -I../../driver/
	gcc -O2 -Wall videoout.c -o videoout -ggdb3 -I../../driver/
	gcc -O2 -Wall getconst.c -o getconst -ggdb3 -I../../driver/
	gcc -O2 -Wall setconst.c -o setconst -ggdb3 -I../../driver/

clean:
	rm -f dpcsync videoout getconst setconst

