<? /* -*- Mode: php -*- */ ?>

<!-- Menu -->
<center>
	<table width="200" border="0" cellspacing="1" cellpadding="0" class="mainclass" bgcolor="white">
		<tr><td align="center" valign="middle" class="menuheader">
			<b>MyHD Linux Driver</b>
		</td></tr>
		<tr><td align="center" valign="middle" class="menuitem">
			<a href="/index.php">Home</a>
		</td></tr>
		<tr><td align="center" valign="middle" class="menuitem">
			<a href="/status.php">Development Status</a>
		</td></tr>
		<tr><td align="center" valign="middle" class="menuitem">
			<a href="/howtohelp.php">How to Help</a>
		</td></tr>
<!--
		<tr><td align="center" valign="middle" class="menuitem">
			<a href="/testcd.php">Bootable Test CD</a>
		</td></tr>
-->
		<tr><td align="center" valign="middle" class="menuitem">
			<a href="/tl880spy.php">TL880Spy Tool</a>
		</td></tr>
		<tr><td align="center" valign="middle" class="menuitem">
			<a href="/myirc.php">MyHD IR Receiver</a>
		</td></tr>
		<tr><td align="center" valign="middle" class="menuitem">
			<a href="/juddertest.php">Judder Test for Linux</a>
		</td></tr>
		<tr><td align="center" valign="middle" class="menuitem">
			<a href="/download.php">Downloads</a>
		</td></tr>
		<tr><td align="center" valign="middle" class="menuitem">
			<a href="/chipsets.php">Card Chipset List</a>
		</td></tr>
		<tr><td align="center" valign="middle" class="menuitem">
			<a href="http://www.sourceforge.net/mail/?group_id=75027">Mailing Lists</a>
		</td></tr>
		<tr><td align="center" valign="middle" class="menuitem">
			<a href="http://www.sourceforge.net/projects/myhd/">SourceForge Project</a>
		</td></tr>
	</table>
</center>

<br>

<!-- News -->
<center>
	<table width="192" border="0" cellspacing="1" cellpadding="0" class="mainclass" bgcolor="white">
		<tr><td align="center" valign="middle" class="menuheader">
			<b>News</b>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New TL880Spy release:</i><br><a href="/download.php#spy1.3">TL880Spy 1.3</a><br>
			<font size="-2">Aug. 11, 2007 16:25:00 MDT</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New release:</i><br><a href="/download.php#0.2.3">MyHD 0.2.3</a><br>
			<font size="-2">Mar. 28, 2007 02:20:00 MDT</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New release:</i><br><a href="/download.php#0.2.2">MyHD 0.2.2</a><br>
			<font size="-2">Jan. 23, 2007 00:35:00 MST</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New tool release:</i><br><a href="/download.php#spy1.2">TL880Spy 1.2</a><br>
			<font size="-2">Jan. 19, 2007 19:30:00 MST</font>
		</td></tr>
<?php
/*
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New release:</i><br><a href="/download.php#0.2.1">MyHD 0.2.1</a><br>
			<font size="-2">Aug. 4, 2006 23:00:00 MDT</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New tool release:</i><br><a href="/download.php#spy1.1">TL880Spy 1.1</a><br>
			<font size="-2">Feb, 16, 2006 00:00:00 MST</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New release:</i><br><a href="/download.php#0.2.0">MyHD 0.2.0</a><br>
			<font size="-2">Feb. 15, 2006 18:30:00 MST</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New release:</i><br><a href="/download.php#0.1.99.2">MyHD 0.1.99.2</a><br>
			<font size="-2">Jan. 25, 2006 13:30:00 MST</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New tool:</i><br><a href="/juddertest.php">Judder Test for Linux</a><br>
			<font size="-2">Jan. 2, 2005 23:30:00 MST</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New release:</i><br><a href="/download.php#0.1.99.1">MyHD 0.1.99.1</a><br>
			<font size="-2">Nov. 18, 2005 15:30:00 MST</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>Great news:</i><br>I'm Back<br>
			<font size="-2">Oct. 20, 2005 01:15:00 MDT</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New release:</i><br><a href="/download.php#0.1.0">MyHD 0.1.0</a><br>
			<font size="-2">Oct. 7, 2003 17:30:00 MDT</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New release:</i><br><a href="/download.php#0.0.7">MyHD 0.0.7</a><br>
			<font size="-2">Oct. 6, 2003 12:00:00 MDT</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New release:</i><br><a href="/download.php#0.0.6">MyHD 0.0.6</a><br>
			<font size="-2">Sep. 22, 2003 15:45:00 MDT</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New tool:</i><br><a href="/tl880spy.php">TL880Spy 1.0</a><br>
			<font size="-2">Aug. 6, 2003 11:45:00 MDT</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New release:</i><br><a href="/download.php#0.0.5">MyHD 0.0.5</a><br>
			<font size="-2">Jun. 25, 2003 11:30:00 MDT</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New release:</i><br><a href="/download.php#0.0.4">MyHD 0.0.4</a><br>
			<font size="-2">Jun. 25, 2003 02:30:00 MDT</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New release:</i><br><a href="/download.php#0.0.3">MyHD 0.0.3</a><br>
			<font size="-2">Jun. 13, 2003 13:30:00 MDT</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New release:</i><br><a href="/download.php#0.0.3b">MyHD 0.0.3b</a><br>
			<font size="-2">May 30, 2003 17:30:00 MDT</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New release:</i><br><a href="/download.php#0.0.3a">MyHD 0.0.3a</a><br>
			<font size="-2">May 30, 2003 13:30:00 MDT</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New section:</i><br><a href="/howtohelp.php">How to Help</a><br>
			<font size="-2">May 27, 2003 12:30:00 MDT</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New release:</i><br><a href="/download.php#0.0.2">MyHD 0.0.2</a><br>
			<font size="-2">May 17, 2003 03:00:00 MDT</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New release:</i><br><a href="/download.php#0.0.1">MyHD 0.0.1</a><br>
			<font size="-2">Mar. 31, 2003 12:45:00 MST</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New section:</i><br><a href="/download.php">Download Driver</a><br>
			<font size="-2">Mar. 31, 2003 12:40:00 MST</font>
		</td></tr>
		<tr><td align="center" valign="middle" class="newsitem">
			<i>New section:</i><br><a href="/chipsets.php">Card Chipset List</a><br>
			<font size="-2">Mar. 20, 2003 15:30:00 MST</font>
		</td></tr>
*/?>
	</table>
</center>

